"""
Users and RBAC Model for FARVS

This module provides database operations for managing user accounts and
role-based access control (RBAC). It handles user creation, authentication,
and role management.

Security Note:
    Passwords must be stored as secure hashes (e.g., PBKDF2, bcrypt, or similar)
    generated by the application. The database stores only the hash bytes,
    never plaintext passwords.

Classes:
    UsersModel: Main class for user CRUD operations
"""

import pyodbc
from typing import Optional, Dict, Any, List

from db.db_connect import get_connection


class UsersModel:
    """
    Database model for managing user accounts and RBAC.
    
    Provides CRUD operations for the Users table:
    - Create: Add new user accounts with password hashes
    - Read: Retrieve user information by username
    - List: Get all users in the system
    """
    
    def create(self, username: str, password_hash: bytes, role: str) -> int:
        """
        Create a new user account.
        
        Args:
            username: Unique username for the user
            password_hash: Hashed password as bytes (use secure hashing algorithm)
            role: User role (e.g., 'Admin', 'Staff', 'Viewer')
        
        Returns:
            int: The ID of the newly created user
        
        Raises:
            pyodbc.Error: If database operation fails or username already exists
        
        Example:
            # In production, hash password properly:
            # password_hash = hashlib.pbkdf2_hmac('sha256', password.encode(), salt, 100000)
            user_id = model.create('admin', password_hash, 'Admin')
        """
        # SQL query to insert user and return the new UserId
        query = (
            "INSERT INTO Users (Username, PasswordHash, Role) OUTPUT INSERTED.UserId VALUES (?, ?, ?)"
        )
        
        with get_connection() as conn:
            cur = conn.cursor()
            # Execute query with parameters
            # Use pyodbc.Binary to properly store binary password hash
            cur.execute(query, (username, pyodbc.Binary(password_hash), role))
            row = cur.fetchone()
            # Return the new user ID
            return int(row[0])

    def get_by_username(self, username: str) -> Optional[Dict[str, Any]]:
        """
        Retrieve a user account by username.
        
        Args:
            username: The username to search for
        
        Returns:
            Dictionary containing user information if found, None otherwise.
            Format: {
                "UserId": int,
                "Username": str,
                "PasswordHash": bytes,
                "Role": str,
                "CreatedAt": datetime,
                "LastLoginAt": datetime or None
            }
        
        Raises:
            pyodbc.Error: If database operation fails
        """
        # SQL query to get user by username
        query = "SELECT UserId, Username, PasswordHash, Role, CreatedAt, LastLoginAt FROM Users WHERE Username = ?"
        
        with get_connection() as conn:
            cur = conn.cursor()
            cur.execute(query, (username,))
            row = cur.fetchone()
            
            # Return None if user not found
            if not row:
                return None
            
            # Return user information as dictionary
            return {
                "UserId": row[0],
                "Username": row[1],
                "PasswordHash": row[2],  # Binary password hash
                "Role": row[3],
                "CreatedAt": row[4],
                "LastLoginAt": row[5],
            }

    def list(self) -> List[Dict[str, Any]]:
        """
        Retrieve all users in the system.
        
        Returns:
            List of dictionaries containing user information (excluding password hashes).
            Each dictionary contains:
            - UserId: int
            - Username: str
            - Role: str
            - CreatedAt: datetime
            - LastLoginAt: datetime or None
        
        Raises:
            pyodbc.Error: If database operation fails
        
        Note:
            Password hashes are excluded from the list for security reasons.
        """
        # SQL query to get all users (excluding password hash for security)
        query = "SELECT UserId, Username, Role, CreatedAt, LastLoginAt FROM Users ORDER BY Username"
        
        with get_connection() as conn:
            cur = conn.cursor()
            cur.execute(query)
            rows = cur.fetchall()
            
            # Convert rows to list of dictionaries
            return [
                {
                    "UserId": r[0],
                    "Username": r[1],
                    "Role": r[2],
                    "CreatedAt": r[3],
                    "LastLoginAt": r[4],
                }
                for r in rows
            ]
    
    def count(self) -> int:
        """
        Get the total count of users in the system.
        
        Returns:
            int: Total number of users
        
        Raises:
            pyodbc.Error: If database operation fails
        """
        query = "SELECT COUNT(*) FROM Users"
        
        with get_connection() as conn:
            cur = conn.cursor()
            cur.execute(query)
            row = cur.fetchone()
            return int(row[0]) if row else 0


