"""
Users and RBAC model stubs.

Provides minimal operations for user creation and lookup. Passwords must be
stored as secure hashes (e.g., PBKDF2, bcrypt, or similar) generated by the
application; the DB stores only the hash bytes.
"""

import pyodbc
from typing import Optional, Dict, Any, List

from db.db_connect import get_connection


class UsersModel:
    def create(self, username: str, password_hash: bytes, role: str) -> int:
        query = (
            "INSERT INTO Users (Username, PasswordHash, Role) OUTPUT INSERTED.UserId VALUES (?, ?, ?)"
        )
        with get_connection() as conn:
            cur = conn.cursor()
            cur.execute(query, (username, pyodbc.Binary(password_hash), role))
            row = cur.fetchone()
            return int(row[0])

    def get_by_username(self, username: str) -> Optional[Dict[str, Any]]:
        query = "SELECT UserId, Username, PasswordHash, Role, CreatedAt, LastLoginAt FROM Users WHERE Username = ?"
        with get_connection() as conn:
            cur = conn.cursor()
            cur.execute(query, (username,))
            row = cur.fetchone()
            if not row:
                return None
            return {
                "UserId": row[0],
                "Username": row[1],
                "PasswordHash": row[2],
                "Role": row[3],
                "CreatedAt": row[4],
                "LastLoginAt": row[5],
            }

    def list(self) -> List[Dict[str, Any]]:
        query = "SELECT UserId, Username, Role, CreatedAt, LastLoginAt FROM Users ORDER BY Username"
        with get_connection() as conn:
            cur = conn.cursor()
            cur.execute(query)
            rows = cur.fetchall()
            return [
                {
                    "UserId": r[0],
                    "Username": r[1],
                    "Role": r[2],
                    "CreatedAt": r[3],
                    "LastLoginAt": r[4],
                }
                for r in rows
            ]


